name: Package Publish dry-run

on:
  push:
    branches: [master]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - uses: dart-lang/setup-dart@v1

      - name: Dry-run publish
        run: flutter pub publish --dry-run
